"""
tools/shap_consistency.py
==========================
Aggregate signed SHAP feature importance across model configurations.

Each trained model writes `top_positive_features` and `top_negative_features`
to its metrics.json (see canary/train/baseline.py), where the sign of
`mean_shap` indicates direction:

    mean_shap > 0  -> feature raises predicted advisory risk
    mean_shap < 0  -> feature lowers predicted advisory risk

This tool aggregates those per-model lists across a set of model directories
(default: the 25 time-split configurations) and reports, per feature and per
direction, the number of models in which the feature appeared among the top
contributors and its mean |SHAP| across those models.

This is the source of record for the praxis SHAP consistency results
(Section 4.4.5 and the feature-family discussion in 4.4.6-4.4.9), replacing
hand-assembled tables. A feature that appears in both directions across
different models is reported under the direction where it appears more often,
with the conflict recorded in the JSON output.

Usage
-----
    # inside the container
    python tools/shap_consistency.py --json data/processed/results/shap_consistency.json

    # a different model set, or more rows
    python tools/shap_consistency.py --glob "data/processed/models/xgb_*_time" --top 20

Output
------
    Console: two ranked tables (risk increasing, risk decreasing).
    JSON: same data, consumed by tools/make_figures.py (figure: shap_consistency).
"""

from __future__ import annotations

import argparse
import glob
import json
import statistics
from collections import defaultdict
from pathlib import Path
from typing import Any

DEFAULT_GLOB = "data/processed/models/*_time"

# Temporal window features encode calendar position rather than plugin-level risk.
# They are the leakage artifact documented in praxis Section 4.4.1 and are excluded
# from reported rankings, matching canary/train/feature_selection.py.
WINDOW_FEATURES = frozenset({"window_index", "window_month", "window_year"})

FAMILY_PREFIXES = {
    "advisory_": "Advisory History",
    "swh_": "Software Heritage",
    "gharchive_": "GitHub Archive",
}


def _family(feature: str) -> str:
    for prefix, name in FAMILY_PREFIXES.items():
        if feature.startswith(prefix):
            return name
    return "Other"


def _magnitude(entry: dict[str, Any]) -> float:
    """Prefer mean_abs_shap; fall back to |mean_shap| or |coefficient|."""
    if "mean_abs_shap" in entry:
        return float(entry["mean_abs_shap"])
    for key in ("mean_shap", "coefficient", "importance"):
        if key in entry:
            return abs(float(entry[key]))
    return 0.0


def aggregate(model_dirs: list[str], include_window: bool = False) -> dict[str, Any]:
    counts: dict[str, dict[str, int]] = {
        "increasing": defaultdict(int),
        "decreasing": defaultdict(int),
    }
    values: dict[str, dict[str, list[float]]] = {
        "increasing": defaultdict(list),
        "decreasing": defaultdict(list),
    }
    used: list[str] = []
    skipped: list[str] = []
    for d in model_dirs:
        path = Path(d) / "metrics.json"
        if not path.exists():
            skipped.append(d)
            continue
        j = json.loads(path.read_text())
        if "top_positive_features" not in j and "top_negative_features" not in j:
            skipped.append(d)
            continue
        used.append(Path(d).name)
        for key, direction in (
            ("top_positive_features", "increasing"),
            ("top_negative_features", "decreasing"),
        ):
            for e in j.get(key, []):
                f = e["feature"]
                if not include_window and f in WINDOW_FEATURES:
                    continue
                counts[direction][f] += 1
                values[direction][f].append(_magnitude(e))

    def rows(direction: str) -> list[dict[str, Any]]:
        out = []
        for f, n in counts[direction].items():
            other = counts["decreasing" if direction == "increasing" else "increasing"].get(f, 0)
            out.append(
                {
                    "feature": f,
                    "family": _family(f),
                    "models": n,
                    "avg_shap": round(statistics.mean(values[direction][f]), 4),
                    "models_opposite_direction": other,
                    "direction_conflict": other >= n,
                }
            )
        return sorted(out, key=lambda r: (-r["models"], -r["avg_shap"]))

    return {
        "_provenance": (
            "Aggregated from top_positive_features / top_negative_features in each model's "
            "metrics.json (signed SHAP, see canary/train/baseline.py). Generated by "
            "tools/shap_consistency.py."
        ),
        "window_features_excluded": sorted(WINDOW_FEATURES) if not include_window else [],
        "n_models_used": len(used),
        "models_used": used,
        "models_skipped_no_metrics": skipped,
        "increasing": rows("increasing"),
        "decreasing": rows("decreasing"),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Aggregate signed SHAP importance across models.")
    parser.add_argument("--glob", default=DEFAULT_GLOB, help="model directory glob")
    parser.add_argument("--top", type=int, default=15, help="rows to print per direction")
    parser.add_argument(
        "--include-window",
        action="store_true",
        help="include temporal window features (excluded by default as leakage artifacts)",
    )
    parser.add_argument("--json", default=None, help="optional JSON output path")
    args = parser.parse_args()

    dirs = sorted(glob.glob(args.glob))
    if not dirs:
        raise SystemExit(f"No model directories matched {args.glob!r}")
    result = aggregate(dirs, include_window=args.include_window)
    n = result["n_models_used"]
    print(f"Aggregated {n} model configurations matching {args.glob!r}")
    if result["models_skipped_no_metrics"]:
        skipped = len(result["models_skipped_no_metrics"])
        print(f"  (skipped {skipped} without SHAP in metrics.json)")

    for direction, label in (
        ("increasing", "RISK INCREASING"),
        ("decreasing", "RISK DECREASING"),
    ):
        print(f"\n{label} (top {args.top} by model consistency)")
        header = f"  {'feature':<44} {'family':<18} {'models':>7} {'avg |SHAP|':>11}"
        print(header)
        print("  " + "-" * (len(header) - 2))
        for r in result[direction][: args.top]:
            flag = "  <-- also appears opposite" if r["direction_conflict"] else ""
            print(
                f"  {r['feature'][:44]:<44} {r['family']:<18} "
                f"{r['models']:>3}/{n:<3} {r['avg_shap']:>11.3f}{flag}"
            )

    if args.json:
        out = Path(args.json)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(result, indent=2), encoding="utf-8")
        print(f"\nSaved: {out}")


if __name__ == "__main__":
    main()
