name: zizmor

on:
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
      - "action.yml"
      - "action.yaml"
      - ".github/workflows/zizmor.yml"
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
      - "action.yml"
      - "action.yaml"
      - ".github/workflows/zizmor.yml"
  workflow_dispatch:

permissions: {}

jobs:
  zizmor:
    name: GitHub Actions security analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@0dce2577a4760a2749d8cfb7a84b7d5585ebcb7d # v0.5.0
        with:
          min-severity: medium
          min-confidence: medium
